=== bmsousa/optimistoolkit/OptimisY3/AdmissionControl/WorkloadAnalyzer/WorkloadAnalyzer-Types/src/main/resources/xsd/workload-analyzer-types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:wl="http://schemas.optimis.eu/workload" 
           targetNamespace="http://schemas.optimis.eu/workload" 
           elementFormDefault="qualified" 
           attributeFormDefault="unqualified">

    <xs:element name="WorkloadAnalysis" type="wl:WorkloadAnalysisType"/>

    <xs:complexType name="WorkloadAnalysisType">
        <xs:sequence>
            <xs:element type="wl:PhysicalHostType" name="PhysicalHost" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="PhysicalHostType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:AssigendServicesType" name="AssigendServices" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:LoadType" name="Load" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:RemainingCapacityType" name="Remaining" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="host_name" use="required"/>
        <xs:attribute type="xs:string" name="public_ip" use="required"/>
        <xs:attribute type="xs:boolean" name="usedForElasticity" use="required"/>
    </xs:complexType>

    <xs:complexType name="AssigendServicesType">
        <xs:sequence>
            <xs:element type="wl:ServiceType" name="Service" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ServiceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="id" use="optional"/>
                <xs:attribute type="xs:string" name="name" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="LoadType">
        <xs:sequence>
            <xs:element type="wl:CurrentType" name="Current" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:MinType" name="Min" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:AverageType" name="Average" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:MaxType" name="Max" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="RemainingCapacityType">
        <xs:sequence>
            <xs:element type="wl:ResourceInformationType" name="ResourceInformation" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ResourceInformationType">
        <xs:sequence>
            <xs:element type="wl:CpuType" name="Cpu" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:CpuCoresType" name="CpuCores" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:CpuSpeedType" name="CpuSpeed" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:MemoryType" name="Memory" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:SwapType" name="Swap" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:StorageType" name="Storage" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:NetworkBandwidthType" name="NetworkBandwidth" minOccurs="0" maxOccurs="1"/>
            <xs:element type="wl:MetricType" name="Metric" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <!-- MIN, AVG, MAX, CURRENT, REMAINING -->
    <xs:complexType name="MaxType">
        <xs:sequence>
            <xs:element type="wl:ResourceInformationType" name="ResourceInformation"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AverageType">
        <xs:sequence>
            <xs:element type="wl:ResourceInformationType" name="ResourceInformation"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CurrentType">
        <xs:sequence>
            <xs:element type="wl:ResourceInformationType" name="ResourceInformation"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MinType">
        <xs:sequence>
            <xs:element type="wl:ResourceInformationType" name="ResourceInformation"/>
        </xs:sequence>
    </xs:complexType>

    <!-- RESOURCES -->
    <xs:complexType name="CpuType">
    	<xs:simpleContent>
    		<xs:extension base="xs:string">
    		    <xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="CpuCoresType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="CpuSpeedType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="MemoryType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="StorageType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="SwapType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="NetworkBandwidthType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="Name" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="ActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    
     <xs:complexType name="MetricType">
        <xs:simpleContent>
    		<xs:extension base="xs:string">
        		<xs:attribute type="xs:string" name="MetricName" use="required"/>
        		<xs:attribute type="xs:string" name="MetricUnit" use="required"/>
        		<xs:attribute type="xs:string" name="MetricActualValue" use="optional"/>
     		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== bmsousa/optimistoolkit/OptimisY3/AdmissionControl/WorkloadAnalyzer/WorkloadAnalyzer-Types/src/main/resources/examples/sample-workload-analyzer-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<wor:WorkloadAnalysis xmlns:wor="http://schemas.optimis.eu/workload" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.optimis.eu/workload ../xsd/workload-analyzer-types.xsd">
  <wor:PhysicalHost id="optimis1" host_name="optimis1" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis1] for hosting VMs</wor:description>
    <wor:AssigendServices/>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="4">4</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">16</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.5</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="8124416">696760</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="8192">6150</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">700249</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">4.784</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">2</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
      <wor:Min>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="4">4</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">16</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.5</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="8124416">296760</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="8192">2150</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">200249</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">1.784</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">0.0</wor:Metric>
        </wor:ResourceInformation>
      </wor:Min>
      <wor:Average>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="4">2</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">8</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.0</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="8124416">496760</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="8192">4150</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">500249</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">2.784</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">2</wor:Metric>
        </wor:ResourceInformation>
      </wor:Average>
      <wor:Max>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="4">3</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">4</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.3</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="8124416">796760</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="8192">7150</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">800249</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">5.500</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">80</wor:Metric>
        </wor:ResourceInformation>
      </wor:Max>
    </wor:Load>
  </wor:PhysicalHost>
  <wor:PhysicalHost id="optimis2" host_name="optimis2" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis2] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="4">4</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">16</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.5</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="9177088">87776</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="6500">4150</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">235985</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">0</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">4</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
  <wor:PhysicalHost id="optimis3" host_name="optimis3" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis3] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="2">2</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="8">6</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.5</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="524288">19612</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="5560">4134</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">668698</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">0</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">20</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
  <wor:PhysicalHost id="optimis4" host_name="optimis4" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis4] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:Cpu Name="number_of_processor" MetricUnit="Processors" ActualValue="1">1</wor:Cpu>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="4">4</wor:CpuCores>
          <wor:CpuSpeed Name="processor_speed" MetricUnit="GHz" ActualValue="3.5">3.5</wor:CpuSpeed>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="978944">70864</wor:Memory>
          <wor:Swap Name="swap_memory" MetricUnit="kB" ActualValue="5800">3540</wor:Swap>
          <wor:Storage Name="storage" MetricUnit="kB">6802</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">.704</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">0.0</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
</wor:WorkloadAnalysis>

=== bmsousa/optimistoolkit/OptimisY3/AdmissionControl/WorkloadAnalyzer/WorkloadAnalyzer-Impl/src/test/resources/workload-analyzer-output.xml
<?xml version="1.0" encoding="UTF-8"?>
<wor:WorkloadAnalysis xmlns:wor="http://schemas.optimis.eu/workload" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.optimis.eu/workload ../xsd/workload-analyzer-types.xsd">
  <wor:PhysicalHost id="optimis1" host_name="optimis1" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis1] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">16</wor:CpuCores>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="8124416">696760</wor:Memory>
          <wor:Storage Name="storage" MetricUnit="kB">700249</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">4.784</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">0.80</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
  <wor:PhysicalHost id="optimis2" host_name="optimis2" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis2] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="16">16</wor:CpuCores>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="9177088">87776</wor:Memory>
          <wor:Storage Name="storage" MetricUnit="kB">235985</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">0</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">0.07</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
  <wor:PhysicalHost id="optimis3" host_name="optimis3" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis3] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="8">6</wor:CpuCores>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="524288">19612</wor:Memory>
          <wor:Storage Name="storage" MetricUnit="kB">668698</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">0</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">1.94</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
  <wor:PhysicalHost id="optimis4" host_name="optimis4" public_ip="192.168.252.1" usedForElasticity="true">
    <wor:description>Insfrastructure Provider's Physical Host [optimis4] for hosting VMs</wor:description>
    <wor:Load>
      <wor:Current>
        <wor:ResourceInformation>
          <wor:CpuCores Name="number_of_cores" MetricUnit="Cores" ActualValue="4">4</wor:CpuCores>
          <wor:Memory Name="main_memory" MetricUnit="kB" ActualValue="978944">70864</wor:Memory>
          <wor:Storage Name="storage" MetricUnit="kB">6802</wor:Storage>
          <wor:NetworkBandwidth Name="netowrk_bandwidth" MetricUnit="Kbps">.704</wor:NetworkBandwidth>
          <wor:Metric MetricName="cpu_load" MetricUnit="%">0.00</wor:Metric>
        </wor:ResourceInformation>
      </wor:Current>
    </wor:Load>
  </wor:PhysicalHost>
</wor:WorkloadAnalysis>
